[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/content.json"
  to = "/.netlify/functions/get-blog-content?uid=:uid&blogId=:blogId"
  status = 200

[[redirects]]
  from = "/users/:uid/blogs/:blogId/api/content/:slug.json"
  to = "/.netlify/functions/get-blog-content?uid=:uid&blogId=:blogId&slug=:slug"
  status = 200

[[redirects]]
  from = "/users/:uid/productSites/:siteId/api/products.json"
  to = "/.netlify/functions/get-product-content?uid=:uid&siteId=:siteId"
  status = 200

[[redirects]]
  from = "/users/:uid/productSites/:siteId/api/products/:slug.json"
  to = "/.netlify/functions/get-product-content?uid=:uid&siteId=:siteId&slug=:slug"
  status = 200

[[redirects]]
  from = "/api/analytics/track"
  to = "/.netlify/functions/track-analytics"
  status = 200

[[redirects]]
  from = "/api/analytics/:uid"
  to = "/.netlify/functions/get-analytics?uid=:uid"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"